# Generated by Django 5.2.9 on 2025-12-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
